# seller-dashboard/netlify.toml

[build]
  # Do not set a base directory if your netlify.toml is already inside seller-dashboard
  # The publish directory is relative to the base
  publish = "public"
  # The functions directory is relative to the base
  functions = "functions"

[[redirects]]
  # This rule correctly proxies requests from the browser to your functions
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200